# Comment to a new issue.
issuesOpened: >
  Thank you for raising an issue. 
  
  The repository maintainer (@grimbough) is currently on parental leave until October 2022 and any response will take longer than usual.

pullRequestOpened: >
  Thank you for creating your pull request.

  The repository maintainer (@grimbough) is currently on parental leave until October 2022 and any response will take longer than usual.
