on:
  push:
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.bioc-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
          os: [ubuntu-20.04, windows-2022, macos-11]
          bioc-version: [release, devel]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
    
      ## R CMD check complains about Windows line endings without this
      - name: Configure git
        run: |
          git config --global core.autocrlf false
    
      - name: Install system libraries
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libcurl4-openssl-dev
          
      - uses: actions/checkout@v1
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
        
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v0
          bioc-version: ${{ matrix.config.bioc-version }}
          bioc-mirror: https://packagemanager.rstudio.com/bioconductor
          
      - uses: r-lib/actions/setup-pandoc@v1
          
      - name: Install dependencies (non-Windows)
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            covr
            rcmdcheck
            
      - name: Session Info
        run: |
          options("BioC_mirror")
          BiocManager::version()
          sessionInfo()
        shell: Rscript {0}
        
      - name: Non-windows check
        if: runner.os != 'Windows'
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual'), error_on = 'warning', check_dir = 'check')"

      - name: Test coverage
        if: ${{ matrix.config.os }} == 'ubuntu-20.04'
        run: |
          covr::codecov()
        shell: Rscript {0}
