on:
  push:
    branches:
      - master
      - new_filters
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: '4.0'}
        - { os: macOS-latest, r: '4.0'}
        - { os: ubuntu-18.04, r: '4.0', rspm: "https://demo.rstudiopm.com/all/__linux__/bionic/latest"}
        - { os: ubuntu-20.04, r: '4.0', rspm: "https://demo.rstudiopm.com/all/__linux__/focal/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.rspm }}

    steps:
      - name: Configure git
        run: |
          git config --global core.autocrlf false
          git config --global user.email "ghau@example.com"
          git config --global user.name "GitHub Actions User"
          
      - name: Install system libraries
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get install libcurl4-openssl-dev
          
      - uses: actions/checkout@v1
          
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('BiocManager', 'remotes'))"
          Rscript -e "BiocManager::install(version = 'devel', ask = FALSE, update = FALSE)"
          Rscript -e "BiocManager::install(c('rcmdcheck', 'devtools'), ask = FALSE, update = FALSE, INSTALL_opts = '--force-biarch')"
          Rscript -e "BiocManager::install('rhdf5', dependencies = TRUE, ask = FALSE, update = FALSE, INSTALL_opts = '--force-biarch')"

      # - name: Non-windows check
      #   if: ${{ matrix.config.os != 'windows-latest' }}
      #   run: |
      #     Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual'), error_on = 'warning', check_dir = 'check')"
      #     
      # - name: Windows check
      #   if: ${{ matrix.config.os == 'windows-latest' }}
      #   run: |
      #     Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual', '--force-multiarch', '--install-args=`"--force-biarch`"'), error_on = 'warning', check_dir = 'check')"

      - name: Build binary
        if: runner.os != 'Linux'
        run: |
          Rscript -e "devtools::build(binary = TRUE, path = ".")"
          
      - name: Upload binary
        if: runner.os != 'Linux'
        uses: actions/upload-artifact@master
        with:
          path: |
            rhdf5*.zip
            rhdf5*.tgz
