on:
  push:
    branches:
      - master
      - new_filters
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: '4.0'}
        - { os: macOS-latest, r: '4.0'}
        - { os: ubuntu-18.04, r: '4.0', rspm: "https://demo.rstudiopm.com/all/__linux__/bionic/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.rspm }}

    steps:
      - name: Configure git
        run: |
          git config --global core.autocrlf false
          git config --global user.email "ghau@example.com"
          git config --global user.name "GitHub Actions User"
          
      - name: Install system libraries
        if: ${{ matrix.config.os == 'ubuntu-18.04' }}
        run: |
          sudo apt-get install libcurl4-openssl-dev
          
      - uses: actions/checkout@v1
          
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('BiocManager', 'remotes'))"
          Rscript -e "BiocManager::install(version = 'devel', ask = FALSE)"
          Rscript -e "BiocManager::install(c('grimbough/Rhdf5lib'), 
                                             version = 'devel', ask = FALSE)"
          Rscript -e "BiocManager::install(c('rcmdcheck', 'rhdf5filters'), 
                                             version = 'devel', ask = FALSE)"
          Rscript -e "BiocManager::install('rhdf5', dependencies = TRUE, 
                                             version = 'devel', ask = FALSE)"

      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning', check_dir = 'check')"
